# version: '3'
# services:
#   node:
#     restart: always
#     build: .
#     environment:
#       DB_SCHEMA: postgres
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       DB_HOST: postgres
#     ports:
#       - 8000:8000
#     volumes:
#       - ./:/code
#     depends_on: ["postgres"]
#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - '5433:5433'
#     volumes:
#       - node-db:/var/lib/postgresql/data
# volumes:
#  node-db:

services:
  node:
    build: .
    restart: always
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - node-db:/var/lib/postgresql/data

volumes:
  node-db:
